name: AutoTrash
version: '${project.version}'
main: me.pizzalover.autotrash.Main
api-version: '1.20'
commands:
  autotrash:
    description: 'Main command for AutoTrash.'
    usage: '/autotrash <add|list|reload>'
